In [6]:
import cv2 as cv
import numpy as np
#Erosion侵蝕
src = cv.imread("C:\Github\NTUST_HW\dye2.png")
src[1:6,1:6] = 1
kernel = np.ones((3,3),np.uint8)

cv.imshow("src",src)
cv.imshow("after erision 5 x 5",dst1)
cv.imshow("after erision 11 x 11",dst2)
cv.waitKey(0)
cv.destroyAllWindows()



src = 
 [[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]
kernel = 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Erosion(侵蝕) = 
 [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
