In [11]:
import torch.nn as nn
import torch
import numpy as np

data =[[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)


tensor([[1, 2],
        [3, 4]])


In [12]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(np_array)

[[1 2]
 [3 4]]


In [13]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones}")
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])
Random Tensor: 
 tensor([[0.0651, 0.2802],
        [0.8654, 0.2975]]) 



In [14]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1605, 0.3495, 0.5434],
        [0.4727, 0.2393, 0.6800]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
